[project]
name = "games_project_pisyapopa"
version = "0.4.0"
description = "Проект для практической работы"
authors = [{name = "pisyapopa"}]

[project.scripts]
vd-main = "games_project_pisyapopa.VD_games.scripts.VD_main:main"
vd-even = "games_project_pisyapopa.VD_games.scripts.VD_even:main"
vd-calc = "games_project_pisyapopa.VD_games.scripts.VD_calc:main"
vd-gcd = "games_project_pisyapopa.VD_games.scripts.VD_gcd:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
